---
name: Test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - development
jobs:
    test:
        name: Test
        concurrency: test_${{ github.head_ref }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Build
              uses: ./.github/actions/build

            - name: Test
              run: yarn test
