name: Determine directories

on:
  workflow_call:
    inputs:
      base-dir:
        required: true
        type: string
    outputs:
      matrix:
        description: "A matrix of directories under base-dir with changes"
        value: ${{ jobs.determine_dirs.outputs.matrix }}

jobs:
  determine_dirs:
    name: Determine directories with changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - id: set-matrix
        name: Set matrix
        run: |
          echo "name=matrix::{\"dir\":$(git diff origin/master HEAD --name-only | xargs dirname | grep ${{ inputs.base-dir }} | cut -d "/" -f1,2 | uniq | jq -Rsc '. / "\n" - [""]')}" >> $GITHUB_OUTPUT
