name: Exit Prerelease Mode

on:
    pull_request:
        branches:
            - main

jobs:
    exit_prerelease:
        name: Changesets Exit Prerelease
        runs-on: ubuntu-latest
        steps:
            # Check if pre.json file exists. The rest of the steps will only run if this file exists
            - name: Check for pre.json file existence
              id: check_files
              uses: andstor/file-existence-action@v3.0.0
              with:
                  files: ".changeset/pre.json"

            - name: Checkout repo
              uses: actions/checkout@v4
              if: steps.check_files.outputs.files_exists == 'true'
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  # Fetch entire git history so  Changesets can generate changelogs
                  # with the correct commits
                  fetch-depth: 0

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v4
              if: steps.check_files.outputs.files_exists == 'true'
              with:
                  node-version: 20

              # Exit prerelease mode
            - name: Exit prerelease mode
              if: steps.check_files.outputs.files_exists == 'true'
              run: yarn changesets pre exit

            - uses: stefanzweifel/git-auto-commit-action@v5
              if: steps.check_files.outputs.files_exists == 'true'
              with:
                  commit_message: Exit prerelease mode
                  # Commit these changes to the branch workflow is running against
                  branch: ${{ github.event.pull_request.head.ref }}
