name: Publish PR
on:
    pull_request:
        branches: [main]
jobs:
    release:
        name: Create canary release
        strategy:
            matrix:
                node: [16.20.0]
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        env:
            NPM_TOKEN: ${{ secrets.WHEREBY_PUBLISH_GITHUB_PACKAGES }}
            GITHUB_TOKEN: ${{ secrets.WHEREBY_PUBLISH_GITHUB_PACKAGES }}
        steps:
            - uses: actions/checkout@v2

            - name: Prepare repository
              run: git fetch --unshallow --tags

            - name: Setup npmrc
              run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: yarn

            - name: Create Release
              run: yarn run auto shipit
